### ISSUE TITLE
Emotes not working

### ISSUE THREAD

**Issue by JiMiKi** [melalawi/GlobalTwitchEmotes#14] opened 2017-10-20 19:01 UTC
Hello, I found another big bug, this time it is related to the latest update of GTE (It never once happened pre-update), if Subscriber Channels Emotes is ticked, in both Twitch.tv and BetterTTV tabs (not sure about FFZ Tab), then any emotes that whole tab would enable, breaks, and they no longer show.

To test this I enabled "Global Twitch.tv Emotes" and googled "LUL Emote" which works fine, it replaces all the LUL's with the LUL emote.

However if I tick "Enable Subscriber Channels Emotes", after a refresh of the same google search page, all the LUL's are now plain text.

Same goes for BetterTTV emotes section, googling FeelsBadMan Emote will work only without channel emotes enabled.

**Comment by melalawi** [comment] 2017-10-20 22:00
I tried following the steps you laid out and I was unable to reproduce the issue.

1) Try pressing shift+F5 to ignore the cache and refresh the page. If the emotes appear after this, that means your browser might be incorrectly caching the images.

In case you're interested, here are the lines of code that are responsible for loading the emote sets into memory:

https://github.com/melalawi/GlobalTwitchEmotes/blob/0e6746bd8ecd8d4797464ecca551a9e30749a80f/src/common/background/emoteManager.js#L41-L76

**Comment by JiMiKi** [comment] 2017-10-21 00:13
Shift + F5 partly solves the issue, now global twitch emotes work, even when Channel Emotes are ticked, but the actual Channel Emotes still do not show at all.

As for BTTV Emotes, they still do not load at all if Channel Emotes is ticked.

Example: https://imgur.com/a/w9SUL

And for each of the screenshots, I did press Shift + F5

These issues only started happening today (I'm guessing it's related to the new update, 1.3?), for both me and my friend who also uses GTE, it just stopped working after a refresh, and has since been broken.

And sorry, I do not understand coding whatsoever, I have no experience or knowledge of it at all.

**Comment by melalawi** [comment] 2017-10-21 00:58
I see.

Can you open a tab where this issue is present, press F12, click on the 'Console' tab in the window that appears, and take a screenshot? 

Thanks.

**Comment by JiMiKi** [comment] 2017-10-21 02:01
Since they all give different results, here are 3 different screenshots

BTTV Emote on Google: https://i.imgur.com/JRokne3.jpg
TwitchEmotes: https://i.imgur.com/wh19bxk.jpg
Twitch App: https://i.imgur.com/m8pi3IK.jpg

**Comment by melalawi** [comment] 2017-10-21 02:12
Those console messages don't seem related to GTE.

1) Does the hover tooltip appear when you try hovering over text that should have converted into an emote?

2) Go to **about://extensions**, scroll down to GTE, click on the 'background page' link, click on the 'console' tab in the window that appears, and post a screenshot.

**Comment by JiMiKi** [comment] 2017-10-21 02:45
Regarding tooltips, they do not appear, it is just plain text as if GTE was not installed at all.

https://pastebin.com/gHC4ndbR not sure if JavaScript is correct, there's a RAW paste at the bottom.
Also had to remove a couple thousand lines to stay within the 512KB limit on Pastebin, though I am fairly sure i did not delete anything that you need, i only removed a ton of identical lines.

Here's the log file itself
[pgniedifoejifjkndekolimjeclnokkb-1508552636366.log](https://github.com/melalawi/GlobalTwitchEmotes/files/1403711/pgniedifoejifjkndekolimjeclnokkb-1508552636366.log)

**Comment by melalawi** [comment] 2017-10-21 03:12
Alright, this says a lot. I'll push a fix for this.

One last thing: Try disabling then enabling the extension via the settings. Then, send me a screenshot of the background page (or a copy of the logs, as you just did). Then try seeing if your issue is resolved.

**Comment by JiMiKi** [comment] 2017-10-21 03:44
Disabling, then enabling, made the Background Page clear out and now it's empty. (I only ticked Enable twice to disable and re-enable)

**Comment by JiMiKi** [comment] 2017-10-21 03:49
When refreshing the TwitchEmotes.com site and the Google Search for the monkaS emote from the screenshot I provided earlier, the Background Page fills up with the errors, though when refreshing app.twitch.tv, the log is still empty.

**Comment by melalawi** [comment] 2017-10-21 04:39
I've pushed a fix for what I think is causing this issue. Try updating all of your extensions from the options page.

![Update Extensions](https://user-images.githubusercontent.com/6510182/31848092-edb7f094-b5ef-11e7-867b-4454bc2466a6.png)

**Comment by JiMiKi** [comment] 2017-10-21 04:47
I've pressed Update 3 times now and the App still says Version 1.3.0 so I am unsure if it successfully updated or not, but the issue is still the same, no noticable changes at all.

**Comment by JiMiKi** [comment] 2017-10-21 04:48
Background Tab still fills up with the same error messages as well

**Comment by melalawi** [comment] 2017-10-21 05:04
The `version_name` should still appear as `1.3.0`. Try updating again in an hour or so. In the meantime, I'll continue running tests on my machine.

**Comment by JiMiKi** [comment] 2017-10-21 05:12
Okay, will do if I don't fall asleep, it's 7 am here x)

**Comment by JiMiKi** [comment] 2017-10-21 07:22
Just tried updating once more and the issue remains the same, no noticable change.

**Comment by melalawi** [comment] 2017-10-21 17:53
Spent a few hours working on this issue. Fix is being pushed to the store.

Thanks for your help. Let me know if the issue is resolved in a few hours.

**Comment by JiMiKi** [comment] 2017-10-21 18:57
The Twitch Channel Emotes now work, but now the extension is completely disabled for app.twitch.tv which makes it, at least to me, pretty useless, as that is where I use GTE to turn text into emotes.

**Comment by melalawi** [comment] 2017-10-21 21:21
I'm glad to see some progress is being made to resolve your issues. I'll be looking at the BTTV problem you're experiencing in a bit.

We can continue discussing the other issue of GTE not running on app.twitch.tv in the other issue you've created.

**Comment by melalawi** [comment] 2017-10-21 22:37
@JiMiKi Can you send me another log dump of the background page after loading a tab with failed BTTV emotes?

**Comment by JiMiKi** [comment] 2017-10-22 06:16
Sorry for the delayed reply. 
Here's the log after trying to make a BTTV Channel Emote appear in a Google search.

[pgniedifoejifjkndekolimjeclnokkb-1508652851583.log](https://github.com/melalawi/GlobalTwitchEmotes/files/1404643/pgniedifoejifjkndekolimjeclnokkb-1508652851583.log)

**Comment by melalawi** [comment] 2017-10-22 07:20
Can you export your settings via the options page and upload the text file here?

Thanks.

**Comment by JiMiKi** [comment] 2017-10-22 07:46
Sure, here you go.

[GTESettings.txt](https://github.com/melalawi/GlobalTwitchEmotes/files/1404692/GTESettings.txt)

**Comment by melalawi** [comment] 2017-10-22 17:39
That did the trick. I've made a little fix, which should be published in a few hours.

Let me know if this particular issue is resolved.

**Comment by JiMiKi** [comment] 2017-10-23 02:20
BTTV emotes now seem to work, both global and channel specific. 
Although, sometimes the emotes can take a while to appear, such as when a tab has been left open for several hours. 
The first time this happened, I thought I had forgot to save my changes when adding BTTV channels and went to check the settings, and noticed that GTE itself was very slow.

![2017-10-23_04-15-48](https://user-images.githubusercontent.com/15256875/31869524-ef6abb00-b7a8-11e7-98ac-04b408e07ef8.jpg)

The menu in the picture above didn't show any buttons or text, just a white box, once they appeared after several seconds and a couple of presses of the icon, loading the settings page took around 1-2 minutes. 
The second time (about 20 minutes ago), I instead refreshed the page straight away when I noticed that emotes showed as plain text, which made the emotes appear immediately and everything went back to normal.

**Comment by melalawi** [comment] 2017-10-23 02:34
I'm glad to see that things seem to be working.

Closing this issue. I've created a separate issue to track progress on the random delays before GTE activates on a page.

**Closed by melalawi** 2017-10-23 02:34 UTC
Labels: bug
