### ISSUE TITLE
Browser stalling due to GTE

### ISSUE THREAD

**Issue by luastoned** [melalawi/GlobalTwitchEmotes#19] opened 2017-11-02 10:08 UTC
Here is a good performance example, for me FF even asks to disable GTE for the tab.

http://ecma-international.org/ecma-262/

**Comment by melalawi** [comment] 2017-11-02 17:57
Hey @luastoned,

I just tested this out and it seems this issue is reproducible on Firefox. I'll look into this further.

Can you try accessing that webpage from Chrome with GTE installed?

Thanks.

**Comment by melalawi** [comment] 2017-11-06 18:15
@luastoned I finished bringing the Firefox version to par with the Chrome version of GTE, which included a lot of performance-based fixes (#17).

The update has just been pushed to AMO. As far as I can tell, the extension no longer stalls when accessing that URL.

Can you please confirm the fix? You might need to manually force Firefox to update GTE:

<img width="954" alt="Firefox Manual Addon Update" src="https://user-images.githubusercontent.com/6510182/32456613-e7211220-c2eb-11e7-9601-3e6ba1712899.png">

Thanks.

**Comment by luastoned** [comment] 2017-11-08 12:24
I'm on 1.3.1011 and it seems fixed.
Why is the code for FF/Chrome different anyway, both should be equal web-extensions?

**Comment by melalawi** [comment] 2017-11-08 17:47
Regardless of Firefox now being compatible with Webextensions, there still exist a few minor differences between it and Chrome's implementation. Namely, Chrome uses a callback-based approach for its extensions API, while Firefox uses promises.

However, the reason for the recent discrepancy between Firefox and Chrome was due to a few bugs which were accidentally pushed to the Chrome store. I needed to sort out those issues before updating the Firefox version.

Closing this issue, now that it has been resolved.

**Closed by melalawi** 2017-11-08 17:47 UTC
Labels: firefox, performance
